version: "3.9"
    
services:
    db:
        image: mysql:5.7.30
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 0.0.0.0:${DATABASE_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        restart: always

volumes:
  db_data: {}